server:
  port: 8083

spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.10.148:9300
  jackson:
    default-property-inclusion: non_null #过滤json字段中值为null的字段
  rabbitmq:
    host: 192.168.10.148
    virtual-host: /leyou
    port: 5672
    username: leyou
    password: leyou

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
#    ribbon:
#      ConnectTimeout: 100000 #请求连接的超时时间，默认时间为1秒
#      ReadTimeout: 100000 #请求处理的超时时间


