server:
  port: 8084
spring:
  application:
    name: goodsweb-server
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.10.148
    virtual-host: /leyou
    username: leyou
    password: leyou
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15