server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://101.37.172.151/hm49?characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Jijie211557!
  rabbitmq:
    host: 192.168.10.148
    port: 5672
    username: leyou
    password: leyou
    virtual-host: /leyou #虚拟机
    template:
      exchange: LEYOU.ITEM.EXCHANGE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo
